### ISSUE TITLE
[STORY] Play against AI

### ISSUE THREAD

**Issue by ozon2** [romuche98/Knight_Wars#9]
**As a** player,
**I want** to be able to play versus an AI **so that** I can have fun playing the game.

## Conditions of satisfaction

- [x] Create a basic AI able to play against the player
- [x] Improve the AI so the game is a little more challenging

**Comment by GauBen** [comment]
Done, see commit 0ac403c59d84fe3907787c9f296f0de2c5f6e9b1

And it's quite challenging to beat
